import PDFDocument from "pdfkit";
import { StripeMetrics } from "./stripe-metrics";

function formatCurrency(amount: number, currency: string) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency.toUpperCase(),
    maximumFractionDigits: 2,
  }).format(amount / 100);
}

type PdfInput = {
  reportId: string;
  accountId: string;
  periodStart: Date;
  periodEnd: Date;
  metrics: StripeMetrics;
};

export async function generateReportPdf(input: PdfInput): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 50 });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk) => chunks.push(chunk as Buffer));

  const finished = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));
  });

  doc.fontSize(18).text("Stripe Investor Report", { align: "left" });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor("#666").text(`Report ID: ${input.reportId}`);
  doc.fontSize(10).fillColor("#666").text(`Stripe Account: ${input.accountId}`);
  doc
    .fontSize(10)
    .fillColor("#666")
    .text(
      `Period: ${input.periodStart.toISOString().slice(0, 10)} → ${input.periodEnd
        .toISOString()
        .slice(0, 10)}`
    );

  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor("#e5e7eb").stroke();
  doc.moveDown();

  doc.fontSize(14).fillColor("#111").text("Key Metrics", { underline: false });
  doc.moveDown(0.5);

  const { metrics } = input;
  const items: Array<[string, string]> = [
    ["Gross volume", formatCurrency(metrics.grossVolume, metrics.currency)],
    ["Net volume", formatCurrency(metrics.netVolume, metrics.currency)],
    ["Fees", formatCurrency(metrics.fees, metrics.currency)],
    ["Refunds", formatCurrency(metrics.refunds, metrics.currency)],
    ["Disputes", formatCurrency(metrics.disputes, metrics.currency)],
    ["Payouts", formatCurrency(metrics.payouts, metrics.currency)],
  ];

  if (typeof metrics.invoiceCount === "number") {
    items.push(["Invoices (paid)", metrics.invoiceCount.toString()]);
  }
  if (typeof metrics.subscriptionCount === "number") {
    items.push(["Subscriptions (active)", metrics.subscriptionCount.toString()]);
  }

  items.forEach(([label, value]) => {
    doc
      .fontSize(11)
      .fillColor("#111")
      .text(label, { continued: true, width: 300 });
    doc.fontSize(11).fillColor("#0f172a").text(value);
  });

  doc.moveDown(1.5);
  doc.fontSize(10).fillColor("#666");
  doc.text(
    "Generated by Proofround with read-only Stripe Connect access. No write or charge permissions were requested."
  );
  doc.moveDown(0.3);
  doc.text("Share this PDF via the investor link. Rotate the link to revoke access.");

  doc.end();
  return finished;
}
